# Proyecto Final Curso: Análisis de Algoritmos parte 2

Contenido del documento:

1. Estudio y comparación de los algoritmos
2. Resultados del estudio
3. Aplicabilidad y caso éxito
4. Conclusiones
5. Bibliografía

# 1.Estudio de los algoritmos

- Autocodificadores variacionales factorizados:

Para comprender el comportamiento de los Autocodificadores variaciones factorizados propuestos en el trabajo "Factorized Variational Autoencoders for Modeling Audience Reactions to Movies" con el fin de identificar las reacciones de los usuarios al ver una serie de películas [ref], es necesario llevar a cabo el estudio de las técnicas que lo conforman: 1) factorización de tensores y 2) factorización de tensores no lineal.





In [22]:
import os
import numpy as np
import pandas as pd
import tensorly as tl

PATH = 'C:/Users/pc/Desktop/Universidad/AnalisisAlgoritmos/Analisis_Algoritmos_Soluciones/ProyectoFinal/dataset/GoldenAgeOfHollywood_networkdata/'
PATHNAME = 'HollywoodGoldenAge_names.txt'
graphs = []

for filename in os.listdir(PATH):
    if filename.endswith("_s2.txt"):
        df = pd.read_csv(PATH+filename, header=None, sep='\t')
        tmp = df.values
        np.fill_diagonal(tmp, 0)
        graphs.append(tmp)

graphs = np.asarray(graphs)
graphs = np.swapaxes(graphs, 0, 2)
graphs = graphs.astype(float)

print(graphs)

names = pd.read_csv(PATH+PATHNAME, header=None, sep=' ').values
names = names[:,0]

print(names)

tensor = tl.sensor(graphs)
        





[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 2.]
  ...
  [0. 0. 0. ... 0. 0. 2.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 2.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 2.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
['Astaire,